# Core Framework
PREFERRED_VERSION_redhawk            = "2.2.1"
PREFERRED_VERSION_bulkiointerfaces   = "2.2.1"
PREFERRED_VERSION_burstiointerfaces  = "2.2.1"
PREFERRED_VERSION_frontendinterfaces = "2.4.4"
PREFERRED_VERSION_redhawk-codegen    = "2.2.1"

# Components
PREFERRED_VERSION_rh-agc                    = "2.0.0"
PREFERRED_VERSION_rh-amfmpmbasebanddemod    = "2.0.0"
PREFERRED_VERSION_rh-arbitraryrateresampler = "2.0.1"
PREFERRED_VERSION_rh-autocorrelate          = "2.0.0"
PREFERRED_VERSION_rh-fastfilter             = "2.0.2"
PREFERRED_VERSION_rh-filereader             = "4.1.0"
PREFERRED_VERSION_rh-filewriter             = "4.1.0"
PREFERRED_VERSION_rh-hardlimit              = "2.0.0"
PREFERRED_VERSION_rh-psd                    = "2.0.2"
PREFERRED_VERSION_rh-psk-soft               = "2.0.1"
PREFERRED_VERSION_rh-rbdsdecoder            = "2.0.1"
PREFERRED_VERSION_rh-siggen                 = "2.0.1"
PREFERRED_VERSION_rh-sinksdds               = "1.0.0"
PREFERRED_VERSION_rh-sinksocket             = "2.0.1"
PREFERRED_VERSION_rh-sinkvita49             = "3.1.0"
PREFERRED_VERSION_rh-sourcesdds             = "1.1.1"
PREFERRED_VERSION_rh-sourcesocket           = "2.1.1"
PREFERRED_VERSION_rh-sourcevita49           = "3.1.0"
PREFERRED_VERSION_rh-tunefilterdecimate     = "2.0.1"

# SoftPkgs
PREFERRED_VERSION_rh-bluefilelib     = "2.1.0"
PREFERRED_VERSION_rh-dsp             = "2.0.0"
PREFERRED_VERSION_rh-fftlib          = "2.1.0"
PREFERRED_VERSION_rh-redhawkdevutils = "4.0.1"
PREFERRED_VERSION_rh-vita49          = "5.0.0"

# Devices
PREFERRED_VERSION_gpp      = "2.2.1"
PREFERRED_VERSION_rtl2832u = "2.1.0"
PREFERRED_VERSION_usrp-uhd = "6.1.0"

# Other deps
PREFERRED_VERSION_rtlsdr = "0.5.2"
PREFERRED_VERSION_xsd    = "4.0.0"
require omniorb-4.2.3.inc
